### ISSUE TITLE
Colaboración guías GCBA

### ISSUE THREAD

**Issue by RacoFernandez** [datosgobar/paquete-apertura-datos#32]
Hola,

Les pasamos los puntos que agregamos en las guías de GCBA para que analicen si son pertinentes para incorporarlas en las de Nación.

1.   Guía para la publicación de datos en formatos abiertos

- Agregamos algunos tipos de formato: kml, geojson, geopackage.

- Sumamos estándares "sectoriales": WKT, GTFS, OC.

- Incluimos la sugerencia de incluir para datos geográficos dos archivos: un CSV con WKT y datos en formato propiamente geo (Geojson, shp).

- Agregamos referencia para entidades de gobierno (muy parcialmente desarrollada hasta tener devolución de SECLyT), las siglas las define un x organismo (SECLyT en GCBA).

- Incluimos una aclaración de cómo levantar un archivo CSV desde un excel para facilitar la accesibilidad.

- En los rangos horarios, hay un error de tipeo: donde va "Jueves de 8 a 12 hs y de 16 a 20 hs -> "JUE__08:12-17:00_16:00-20:00"" debería ir "Jueves de 8 a 12 hs y de 16 a 20 hs -> "JUE__08:00-12:00_16:00-20:00"".

2. Guía para la identificación y uso de entidades interoperables

- Aclaramos que los nomencladores de INDEC son dinámicos y pueden cambiar, que los citados refieren al Censo 2010.

- Desarrollamos las particularidades de CABA que ustedes mencionan, escribimos la interoperabilidad dentro de CABA, en la guía de Nación menciona que es una particularidad y los motivos. Si quieren, podemos pasarles un párrafo con la interoperabilidad de CABA o pueden referenciar directamente a la guía de GCBA.

3. Guía para el uso y la publicación de metadatos

- Agregamos Normativa aplicable a la Protección y Clasificación según Normativa como campos de la metadata de distribución.

La guía de metadatos es la con la que más estamos trabajando ahora ya que no agregamos tantos cambios. Cuando haya nuevos, abrimos otro issue.

Muchas gracias!! Cualquier duda avisen.

**Comment by abenassi** [comment]
Hola, incorporamos varios de los puntos (gracias!). Abajo van algunos
comentarios sobre c/u.

Les pasamos los puntos que agregamos en las guías de GCBA para que analicen
> si son pertinentes para incorporarlas en las de Nación.
>
>    1. Guía para la publicación de datos en formatos abiertos
>
>
>    -
>
>    Agregamos algunos tipos de formato: kml, geojson, geopackage.*
>    (Buenísimo! Lo incorporarmos. Por qué no agregaron SHP? Entendemos que
>    sería "el XLSX de los datos geográficos")*
>    -
>
>    Sumamos estándares "sectoriales": WKT, GTFS, OC. *(Para nosotros, los
>    estándares sectoriales serían parte de una sección en la guía de entidades
>    interoperables. La guía de formatos abiertos busca ser más genérica. WKT
>    sin embargo nos parece suficientemente genérico para estar en la guía de
>    abiertos porque alcanza a todos los datos geográficos concebibles sin
>    perder vigencia. GTFS y Open Contracting sí ya son temáticos / sectoriales)*
>    -
>
>    Incluimos la sugerencia de incluir para datos geográficos dos
>    archivos: un CSV con WKT y datos en formato propiamente geo (Geojson, shp).
>    -
>
>    Agregamos referencia para entidades de gobierno (muy parcialmente
>    desarrollada hasta tener devolución de SECLyT), las siglas las define un x
>    organismo (SECLyT en GCBA).
>    -
>
>    Incluimos una aclaración de cómo levantar un archivo CSV desde un
>    excel para facilitar la accesibilidad. *(No encuentro esta aclaración
>    en la adaptación de ustedes, me podrás señalar el párrafo que agregaron?)*
>    -
>
>    En los rangos horarios, hay un error de tipeo: donde va "Jueves de 8 a
>    12 hs y de 16 a 20 hs -> "JUE__08:12-17:00_16:00-20:00"" debería ir "Jueves
>    de 8 a 12 hs y de 16 a 20 hs -> "JUE__08:00-12:00_16:00-20:00"".
>
>
>    1. Guía para la identificación y uso de entidades interoperables
>
>
>    -
>
>    Aclaramos que los nomencladores de INDEC son dinámicos y pueden
>    cambiar, que los citados refieren al Censo 2010.
>    -
>
>    Desarrollamos las particularidades de CABA que ustedes mencionan,
>    escribimos la interoperabilidad dentro de CABA, en la guía de Nación
>    menciona que es una particularidad y los motivos. Si quieren, podemos
>    pasarles un párrafo con la interoperabilidad de CABA o pueden referenciar
>    directamente a la guía de GCBA. *(Creo que estaría bueno hacer ambas
>    cosas. Nos pasás el párrafo así lo incorporamos?)*
>
>
>    1. Guía para el uso y la publicación de metadatos
>
>
>    - Agregamos Normativa aplicable a la Protección y Clasificación según
>    Normativa como campos de la metadata de distribución.
>
> La guía de metadatos es la con la que más estamos trabajando ahora ya que
> no agregamos tantos cambios. Cuando haya nuevos, abrimos otro issue.
>
> Muchas gracias!! Cualquier duda avisen.
>

**Comment by abenassi** [comment]
@RacoFernandez ahí ya encontré el párrafo donde explican el caso GCBA. Dejamos una parte y referenciamos para el detalle a la guia de GCBA. Gracias!

**Comment by abenassi** [comment]
Buenísimo, gracias a ustedes1
